/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dongseoki.http.client;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.Arrays;

public class App {

  public static void main(String[] args) throws IOException {
    App app = new App();
    app.run();
  }

  private void run() throws IOException {
    System.out.println("hello world");
    // 1 connect
    Socket socket = new Socket("example.com", 80);
    String message = """
        GET / HTTP/1.1
        Host: example.com
                
        """;

    // 2 request
    // Writer를 쓰면 편리!
    OutputStream outputStream = socket.getOutputStream();
    outputStream.write(message.getBytes());
    System.out.println("write complete!");

    // 3 response
    //Reader 를 쓰면 편리!
    InputStream inputStream = socket.getInputStream();
    byte[] bytes = new byte[1_000_000];
    int size = inputStream.read(bytes);
    byte[] data = Arrays.copyOf(bytes, size);
    System.out.println("data = " + new String(data));
    System.out.println("response complete");

    // 4 close

    socket.close();
    System.out.println("socket close complete");
    // try - with resource를 쓰면 편리..!
  }
}
