/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dongseoki.http.server;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class App {

  public static void main(String[] args) throws IOException {
    App app = new App();
    app.run();
  }

  private void run() throws IOException {


    while (true) {
      // 3 listen
      ServerSocket listener = new ServerSocket(8080);
      // 4 accept
      Socket socket = listener.accept();

      // 5 request
      // 위에 다룬것과 동일하니 생랴.

      // 6 response
      String body = "Hello, world!";
      byte[] bytes = body.getBytes();
      String message = "" +
          "HTTP/1.1 200 OK\n" +
          "Content-Type: text/html; charset=UTF-8\n" +
          "Content-Length: " + bytes.length + "\n" +
          "\n" +
          body;
      // 6-2 전송
      OutputStreamWriter writer = new OutputStreamWriter(socket.getOutputStream());

      writer.write(message);
      writer.flush();

      // 7 종료 닫기.
      socket.close();
      // 서버 소켓 닫기.
      listener.close();
    }


  }
}
